environment: develop

sqldriver: mysql
user: ${Go_P_Zo_DB_USER}
password: ${Go_P_Zo_DB_PASSWORD}
protocol: tcp
address: ${Go_P_Zo_DB_ADDRESS}
database: Go_P_Zo?parseTime=true&loc=Local

auth:
  token_expiration: 43200
  usertoken_expiration: 1200
  signkey: ${Go_P_Zo_AUTH_SIGNKEY}
